version: "3.9"

services:
  bwapp:
    build: .
    container_name: bwapp
    restart: unless-stopped
    # Uncomment bleow lines to make bwapp accesible by localhost:8080
    # Only use this when needed for debuging.    
#   ports:
#     - "8080:80"
    volumes:
      - bwapp_data:/var/lib/mysql

  nginx:
    image: owasp/modsecurity-crs:nginx
    container_name: nginx
    environment:
      - BACKEND=http://bwapp:80/
      - MODSEC_RULE_ENGINE=On
      - PARANOIA=1
      - PORT=8080
      - SSL_PORT=8443
      - CERTIFICATE_TYPE=SELF_SIGNED
    ports:
      - "80:8080"
      - "443:8443"

volumes:
  bwapp_data:
